### PR TITLE
Various NZ Councils Cem D/base Search Links

### PR DESCRIPTION
**Pull request by RAMINCNZ**
Various New Zealand Councils Cemetery Database search links. More will be added as I use them.

### CODE REVIEW

**Comment by kiwi3685** [comment]
Rick, glad to see these created. Good job. 
But a few could be improved by adding search details like individuals names, where the webpage is designed to allow it. 
Hamilton CC is an example:

_https://hamilton.govt.nz/cemeteries/cemetery-search/?searchby=name&keywords=Ross%20Jansen_

Instructions to do this are included with the module.

Nigel

**Comment by RAMINCNZ** [comment]
Nigel

I will look at that a bit more.. The penny did drop the other day about your improvement.

There a lot more of these and it would be really good if it were possible to create a category such as Northland, Auckland, Coromandel, Waikato (being a few of NZ Regions. Then beneath each category one could add appropriate councils. Each Category would expand or close upon clicking that category 'link'.. 

Also the various cemeteries each Council maintains can be quite long.. Auckland for example has heaps, so for those who are not as aware of NZ regions Councils etc may have difficulty figuring the right Council to check a cemetery.. 

My thoughts may go beyond Carmens Fancy Research Links Module, however I hope she and or those who are by far better than I at coding might figure it out..

Rick M

**Comment by JustCarmen** [comment]
Thanks!

**Comment by kiwi3685** [comment]
Small problem. This group includes one for NZBMDs. But there are already three similar that link to the individual NZBDM-births, NZBDM-marriages, and NZBDM-deaths.

**Pull request merged**
